
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    tier: app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30225
