
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-service
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  selector:
    matchLabels:
      app: db 
  serviceName: "mongodb-service"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: db 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mongo:4
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mypvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mypvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

