
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

bases:
  - ../../base

resources:
  - api/
  - db/
  - monitoring/
configMapGenerator:
  - name: db-config
    files:
      - postgresql.conf
patches:
  - db-patch.yaml
namespace: prod
patchesStrategicMerge:
  - api-deployment-patch.yaml
  - db-deployment-patch.yaml

components: 
  - ../../components/auth
nameSuffix: -prod

replicas:
  name: api-deployment
  value: 5

patches:
  - target:
      apiVersion: apps/v1
      kind: Deploymemt
      name: db-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: db
          image: mongo