app:
  deployment:
    name: app-deployment
    replicas: 5
    strategy: RollingUpdate
    image: macarious25siv/project
    imageTag: NodeV5
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    containerPort: 5000
    env:
      value:
        MONGODB_URI: "mongodb://db-statefulset-0.mongodb-service.default.svc.cluster.local:27017"
  service:
    name: app-service
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30225
