apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app

  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - name: nodejs
          image: macarious25siv/project:NodeV5
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # envFrom:
          # - configMapRef:
          #     name: mykustom-map
          # # env:
          # #   - name: MONGODB_URI
          # #     value: "mongodb://mongodb-service.mac.svc.cluster.local:27017/test"

