apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: app
  # strategy:
  #   type: RollingUpdate
  # strategy:
  #   type: Recreate
  # strategy:
  #   type: Canary

  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - name: nodejs
          image: macarious25siv/project:NodeV5
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: mykustom-map
          # env:
          #   - name: MONGODB_URI
          #     value: "mongodb://mongodb-service.mac.svc.cluster.local:27017/test"


---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    tier: app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30225
  # type: ClusterIP
  # ports:
  #   - port: 5000
  #     targetPort: 5000
  #     protocol: TCP