apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
            - "--config.file=/etc/prometheus/prometheus.yml"
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus/
      volumes:
      - name: config-volume-prometheus
        configMap:
          name: prometheus-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  selector:
    name: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30090
